spring.application.name=SpringBoot-03_RealTimeDependecyMgmt-4


emp.info.id=43125
emp.info.name=Narendar
emp.info.company.name=ABCD
emp.info.company.location=Thane
emp.info.company.size=35

#Array object injection
emp.info.skill-set[0]=Java
emp.info.skill-set[1]=JEE
emp.info.skill-set[2]=ORM
emp.info.skill-set[3]=Spring


#List object injection
emp.info.projects[0]=SuperApp
emp.info.projects[1]=ServiceApp
emp.info.projects[2]=LMS

#Set object injection
emp.info.mobile-number[0]=9137364564
emp.info.mobile-number[1]=9838771315
emp.info.mobile-number[2]=9820466103

#Map object injection
emp.info.id-details.adharNo=503843620477
emp.info.id-details.panNO=CLRPN2493Q
emp.info.id-details.voterId=123654
