spring.application.name=SpringBoot-LogginExample
course.choose=dotnet

INFO = true
logging.level.in.nkn.dependent=DEBUG
logging.file.name=log.txt
logging.pattern.file=%c %r %t %m %d %n
logging.pattern.console=%30c %r [%t] %p %m %d %L %F %n
