spring.application.name=SpringBoot-03_RealTimeDependecyMgmt-3

spring.datasource.url=jdbc:mysql:///spring_core
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=9091